### ISSUE TITLE
NX/OS - Extraction of software_version from Cisco Call Home

### ISSUE THREAD

**Issue by guilhemmarchand** [inspired/cisco_ios#2]
Hi,

Currently, the software_version fails from being extracted for NX/OS devices, adding the following field alias in props.conf of your Cisco addon does the job:

[Cisco:SmartCallHome]
# For NX/OS

FIELDALIAS-sch_fields-100 = "soap-env:Envelope.soap-env:Body.aml-block:Block.aml-block:Header.aml-block:Builder.aml-block:Version" AS software_version

According to your configuration, i have arbitrary choose a "sh_fields-100" name.

Thank you !

Guilhem

**Comment by inspired** [comment]
Hi, I implemented this as:

EVAL-software_version = mvappend('soap-env:Envelope.soap-env:Body.aml-block:Block.aml-block:Content.ch-inv:CallHome.ch-inv:Device.rme:Chassis.rme:Card.rme:SoftwareIdentity.rme:VersionString', 'soap-env:Envelope.soap-env:Body.aml-block:Block.aml-block:Header.aml-block:Builder.aml-block:Version')

Could you please test commit 2e40486e603718ac16d4903a6ee12267604c4018?

**Comment by guilhemmarchand** [comment]
Hi, thank you !

This will be tested today, will update as soon as possible.
