### ISSUE TITLE
nav menu options: Showing back Reports, Alerts and Dashboards default menu

### ISSUE THREAD

**Issue by guilhemmarchand** [inspired/cisco_ios#3]
Hello,

The default.xml for the application navigation menu will not show default Splunk interfaces for Reports, Alerts and Dashboards menus.

These are now Splunk standard since 6.x Splunk main version, is that possible to put back these menus by default ?

In:

default/data/ui/nav/default.xml

Adding:

```
<view name="reports" />
<view name="alerts" />
<view name="dashboards" />
```

Removing these menus introduces confusion for Splunk 6.x users that won't be able to find easily their own objects like custom dashboards or reports.

Thank you !

**Comment by inspired** [comment]
Agreed. Merged :-)
