### ISSUE TITLE
jQuery 3.5 Compatibility

### ISSUE THREAD

**Issue by MrMRV** [inspired/cisco_ios#9]
Hi Guys,

Thanks a lot for your work! Very very useful!
But do you think to update the app to jQuery 3.5?
I saw that the app doesn't pass the jQuery 3.5 test on Splunk Cloud.

![image](https://user-images.githubusercontent.com/72919417/143016815-b181e881-2a5f-47f0-922e-982bde9f3ced.png)

Thanks a lot!
Regards,
M.

**Comment by inspired** [comment]
Thanks for letting me know. Fixed in 9fea493c8cce4fc283d1892f68509665e823883a
Will upload to Splunkbase shortly.

**Comment by MrMRV** [comment]
HI Ispired,

Very very very very many thanks! =)
Have a nice day!

M.

**Comment by inspired** [comment]
Released as 2.7.2 and shipped to Splunkbase :-)

https://github.com/inspired/cisco_ios/releases/tag/v2.7.2
